version: '3'
services:
  php:
    image: php:8.1-fpm
    restart: always
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./.docker/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
